### ISSUE TITLE
Libretro Execution Failure

### ISSUE THREAD

**Issue by zach-morris** [SquirrelJME/SquirrelJME#49] opened 2019-08-08 17:44 UTC
Attempting to load any Java ME jar file using the libretro implementation results in an execution failure.

Log:
```
xxxs-MacBook-Pro:~ xxx$ /Applications/RetroArch.app/Contents/MacOS/RetroArch -L "/Users/xxx/Documents/RetroArch/cores/squirreljme_libretro.dylib" "/Users/xxx/Downloads/BilliardBerzerkMidlet.jar"
...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] SquirrelJME Run-Time 0.3.0
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] VM: SquirrelJME RatufaCoat 0.3.0
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] (C) Stephanie Gawroriski
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] RAM/ROM (bytes): 16777216/12874564
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] 
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Initializing task manager...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Okay.
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] 
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Creating initial task...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Scanning 57 libraries...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Okay.
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Using firmware class path!
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Initializing task 1 (1)...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Finding class cc/squirreljme/runtime/launcher/ui/MidletMain...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Initializing class info cc/squirreljme/runtime/launcher/ui/MidletMain...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Searching for ClassInfo...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Finding class cc/squirreljme/jvm/ClassInfo...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] Initializing class info cc/squirreljme/jvm/ClassInfo...
[INFO] Environ GET_LOG_INTERFACE.
[libretro INFO] JVM execution failure: fffffff0 0000a000
[INFO] Environ GET_LOG_INTERFACE.
[libretro ERROR] SquirrelJME JVM Exec Error: -12/fffffff4 5351798/0051a976
[libretro ERROR] Execution now unpredictable!
```

<img src="https://i.imgur.com/dRA1uGs.png" width="350">

**Comment by XerTheSquirrel** [comment] 2019-08-10 16:56
The bootloader is currently incomplete thus the error. Please do see https://github.com/XerTheSquirrel/SquirrelJME/issues/48 .

**Comment by XerTheSquirrel** [comment] 2019-09-16 13:37
Marking duplicate of new pinned issue #53, issues will be tracked here.

**Closed as completed by XerTheSquirrel** 2019-09-16 13:37 UTC
Labels: duplicate
